"""Add PendingSTKPush model for persistent STK Push tracking

Revision ID: 0c75d437705f
Revises: 36ba5e5da03a
Create Date: 2026-06-05 23:08:38.526678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c75d437705f'
down_revision = '36ba5e5da03a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_stk_pushes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('checkout_request_id', sa.String(length=128), nullable=False),
    sa.Column('tab_id', sa.String(length=36), nullable=True),
    sa.Column('payment_id', sa.String(length=36), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_stk_pushes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_stk_pushes_checkout_request_id'), ['checkout_request_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pending_stk_pushes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pending_stk_pushes_checkout_request_id'))

    op.drop_table('pending_stk_pushes')
    # ### end Alembic commands ###
