"""Booking occupants: name every adult staying, not just the payer

Revision ID: 1fbe81ace9af
Revises: 4e102441e582
Create Date: 2026-08-29 08:26:59.898283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fbe81ace9af'
down_revision = '4e102441e582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_occupants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_adult', sa.Boolean(), nullable=False),
    sa.Column('may_charge', sa.Boolean(), nullable=False),
    sa.Column('checked_out_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('booking_occupants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_occupants_booking_id'), ['booking_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_occupants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_occupants_booking_id'))

    op.drop_table('booking_occupants')
    # ### end Alembic commands ###
