"""q3_2_safety_check_items_column

Revision ID: 26bb95623255
Revises: 0c75d437705f
Create Date: 2026-06-08 12:29:28.727607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26bb95623255'
down_revision = '0c75d437705f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safety_checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('check_items', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('safety_checks', schema=None) as batch_op:
        batch_op.drop_column('check_items')

    # ### end Alembic commands ###
