"""chunk 2 inventory models

Revision ID: 2a09d1427a39
Revises: f21842b19019
Create Date: 2026-05-28 02:18:32.469470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a09d1427a39'
down_revision = 'f21842b19019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('reorder_level', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('is_watch_list', sa.Boolean(), nullable=False),
    sa.Column('tolerance_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_staff_food', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('reorder_level >= 0', name='ck_item_reorder_nonneg'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'department_id', name='uq_item_name_dept')
    )
    op.create_table('judge_baselines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('business_driver', sa.String(length=100), nullable=False),
    sa.Column('expected_ratio', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('driver_unit', sa.String(length=50), nullable=False),
    sa.Column('tolerance_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('expected_ratio > 0', name='ck_baseline_ratio_pos'),
    sa.CheckConstraint('tolerance_percent > 0', name='ck_baseline_tol_pos'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'business_driver', name='uq_baseline_item_driver')
    )
    op.create_table('judge_alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=True),
    sa.Column('item_description', sa.String(length=200), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('requested_by_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('manager_id', sa.String(length=36), nullable=True),
    sa.Column('manager_notes', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('owner_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('item_id IS NOT NULL OR item_description IS NOT NULL', name='ck_preq_item_or_desc'),
    sa.CheckConstraint('quantity > 0', name='ck_preq_qty_pos'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_counts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('counted_amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.CheckConstraint('counted_amount >= 0', name='ck_count_nonneg'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_counts_item_id'), ['item_id'], unique=False)

    op.create_table('stock_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('change_amount', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('reason', sa.String(length=30), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.CheckConstraint('change_amount != 0', name='ck_movement_nonzero'),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_item_id'), ['item_id'], unique=False)

    op.create_table('purchases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('purchase_request_id', sa.String(length=36), nullable=True),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('actual_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('receipt_photo_path', sa.String(length=500), nullable=False),
    sa.Column('supplier_name', sa.String(length=200), nullable=True),
    sa.Column('recorded_by_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp_asked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_delivered', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timestamp_added', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('movement_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint('actual_cost >= 0', name='ck_purchase_cost_nonneg'),
    sa.CheckConstraint('quantity > 0', name='ck_purchase_qty_pos'),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['stock_movements.id'], ),
    sa.ForeignKeyConstraint(['purchase_request_id'], ['purchase_requests.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases')
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_item_id'))

    op.drop_table('stock_movements')
    with op.batch_alter_table('stock_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_counts_item_id'))

    op.drop_table('stock_counts')
    op.drop_table('purchase_requests')
    op.drop_table('judge_alerts')
    op.drop_table('judge_baselines')
    op.drop_table('inventory_items')
    # ### end Alembic commands ###
