"""chunk 5 HR clock-in shifts leave

Revision ID: 2d17387f9e59
Revises: 69642070071a
Create Date: 2026-05-28 22:30:33.606816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d17387f9e59'
down_revision = '69642070071a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wifi_allow_list',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ssid', sa.String(length=100), nullable=False),
    sa.Column('ip_cidr', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('national_id', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=30), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('wage_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('wage_period', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('leave_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('leave_type', sa.String(length=12), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name='ck_leave_end_after_start'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leave_requests_employee_id'), ['employee_id'], unique=False)

    op.create_table('shifts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_start_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_end_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role_on_shift', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('scheduled_end_utc > scheduled_start_utc', name='ck_shift_end_after_start'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shifts_employee_id'), ['employee_id'], unique=False)

    op.create_table('absence_notices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('expected_shift_id', sa.String(length=36), nullable=True),
    sa.Column('notice_type', sa.String(length=10), nullable=False),
    sa.Column('expected_late_minutes', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('sent_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['expected_shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('absence_notices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_absence_notices_employee_id'), ['employee_id'], unique=False)

    op.create_table('clock_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=12), nullable=False),
    sa.Column('occurred_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_ip', sa.String(length=45), nullable=True),
    sa.Column('source_wifi_ssid', sa.String(length=100), nullable=True),
    sa.Column('shift_id', sa.String(length=36), nullable=True),
    sa.Column('is_manual_override', sa.Boolean(), nullable=False),
    sa.Column('override_by_id', sa.String(length=36), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['override_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('clock_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clock_events_employee_id'), ['employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clock_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clock_events_employee_id'))

    op.drop_table('clock_events')
    with op.batch_alter_table('absence_notices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_absence_notices_employee_id'))

    op.drop_table('absence_notices')
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shifts_employee_id'))

    op.drop_table('shifts')
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leave_requests_employee_id'))

    op.drop_table('leave_requests')
    op.drop_table('employee_profiles')
    op.drop_table('wifi_allow_list')
    # ### end Alembic commands ###
