"""add DRAFT status and system_generated to purchase_requests

Revision ID: 2ec75d138772
Revises: 943bcf64838d
Create Date: 2026-06-17 06:32:31.921607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec75d138772'
down_revision = '943bcf64838d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_generated', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.alter_column('requested_by_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.alter_column('requested_by_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('system_generated')

    # ### end Alembic commands ###
