"""widen signature_proof to Text for base64 PNG

Revision ID: 3089529f3445
Revises: 26bb95623255
Create Date: 2026-06-10 16:18:32.466758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3089529f3445'
down_revision = '26bb95623255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waivers', schema=None) as batch_op:
        batch_op.alter_column('signature_proof',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waivers', schema=None) as batch_op:
        batch_op.alter_column('signature_proof',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###
