"""bookings.credit_limit: a room needs a ceiling like a wristband has

Revision ID: 308b888ddceb
Revises: 5c3f9c4ee345
Create Date: 2026-09-14 16:11:10.467558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '308b888ddceb'
down_revision = '5c3f9c4ee345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Plain ADD COLUMN, not batch_alter_table. Batch mode recreates the whole
    # table on SQLite — copying every row and re-declaring every constraint —
    # which is a real risk on bookings for a column that is merely nullable.
    # SQLite supports ADD COLUMN natively, so nothing needs rebuilding.
    op.add_column('bookings', sa.Column('credit_limit', sa.Numeric(precision=14, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'credit_limit')

    # ### end Alembic commands ###
