"""Add bank_ref column to Payment for bank transfer references

Revision ID: 36ba5e5da03a
Revises: 59a665201296
Create Date: 2026-06-05 12:43:21.711770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ba5e5da03a'
down_revision = '59a665201296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_ref', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('bank_ref')

    # ### end Alembic commands ###
