"""Add station_rosters table

Revision ID: 3a335b98e8dc
Revises: 8e94a7bbcb48
Create Date: 2026-08-25 17:26:31.855032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a335b98e8dc'
down_revision = '8e94a7bbcb48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('station_rosters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('roster_date', sa.Date(), nullable=False),
    sa.Column('assigned_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'roster_date', name='uq_roster_user_date')
    )
    with op.batch_alter_table('station_rosters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_station_rosters_roster_date'), ['roster_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_station_rosters_user_id'), ['user_id'], unique=False)

    # NOTE: deliberately NOT adding the tabs.assigned_to_id FK constraint that
    # autogenerate also wanted here — see the previous migration's comment
    # (8e94a7bbcb48): SQLite can only add it via a full table recreate, which
    # fails on live data because charges/payments/orders hold FKs into tabs.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('station_rosters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_station_rosters_user_id'))
        batch_op.drop_index(batch_op.f('ix_station_rosters_roster_date'))

    op.drop_table('station_rosters')
    # ### end Alembic commands ###
