"""chunk 6 bookings villas deposits waivers

Revision ID: 3ea9e71a2a1e
Revises: 2d17387f9e59
Create Date: 2026-05-28 23:32:25.123168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea9e71a2a1e'
down_revision = '2d17387f9e59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_visit_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('bookable_resources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('base_price >= 0', name='ck_resource_price_nonneg'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('guest_record_id', sa.String(length=36), nullable=True),
    sa.Column('guest_name', sa.String(length=200), nullable=False),
    sa.Column('guest_phone', sa.String(length=30), nullable=False),
    sa.Column('guest_id_number', sa.String(length=50), nullable=True),
    sa.Column('number_of_guests', sa.Integer(), nullable=False),
    sa.Column('check_in_planned_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out_planned_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_in_actual_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_actual_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('deposit_required', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('tab_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('base_total >= 0', name='ck_booking_total_nonneg'),
    sa.CheckConstraint('check_out_planned_utc > check_in_planned_utc', name='ck_booking_checkout_after_checkin'),
    sa.CheckConstraint('deposit_required >= 0', name='ck_booking_deposit_nonneg'),
    sa.CheckConstraint('number_of_guests > 0', name='ck_booking_guests_pos'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['guest_record_id'], ['guest_records.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['bookable_resources.id'], ),
    sa.ForeignKeyConstraint(['tab_id'], ['tabs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_resource_id'), ['resource_id'], unique=False)

    op.create_table('booking_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=10), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    with op.batch_alter_table('booking_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_booking_payments_booking_id'), ['booking_id'], unique=False)

    op.create_table('waivers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=False),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('signed_by_name', sa.String(length=200), nullable=False),
    sa.Column('signature_proof', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('signed_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waivers_booking_id'), ['booking_id'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.alter_column('tab_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('tab_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('description')

    with op.batch_alter_table('waivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waivers_booking_id'))

    op.drop_table('waivers')
    with op.batch_alter_table('booking_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_booking_payments_booking_id'))

    op.drop_table('booking_payments')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_resource_id'))

    op.drop_table('bookings')
    op.drop_table('bookable_resources')
    op.drop_table('guest_records')
    # ### end Alembic commands ###
