"""add image_path to menu_items

Revision ID: 3fae5c3ad830
Revises: f0a9f08fd38c
Create Date: 2026-06-18 04:00:40.333530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fae5c3ad830'
down_revision = 'f0a9f08fd38c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
