"""employees carry a weekly working pattern so shifts generate instead of being typed

Revision ID: 3fcff8c95b91
Revises: a0cd2d0a4b60
Create Date: 2026-09-01 14:10:58.728790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fcff8c95b91'
down_revision = 'a0cd2d0a4b60'
branch_labels = None
depends_on = None


# Plain add_column, not batch_alter_table: batch rebuilds the whole table and
# employee_profiles is referenced by shifts and clock_events, so the rebuild
# trips a foreign-key failure and leaves a stray temp table behind.
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_profiles', sa.Column('roster_days', sa.String(length=60), nullable=True))
    op.add_column('employee_profiles', sa.Column('roster_start', sa.String(length=5), nullable=True))
    op.add_column('employee_profiles', sa.Column('roster_end', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_profiles', 'roster_end')
    op.drop_column('employee_profiles', 'roster_start')
    op.drop_column('employee_profiles', 'roster_days')

    # ### end Alembic commands ###
