"""Menu: is_alcoholic — chef authors food + juices, manager owns the liquor list

Revision ID: 4e102441e582
Revises: e88eb8ef1962
Create Date: 2026-08-29 05:58:37.270064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e102441e582'
down_revision = 'e88eb8ef1962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_alcoholic', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('is_alcoholic')

    # ### end Alembic commands ###
