"""make Payment.received_by_id nullable for Daraja automated payments

Revision ID: 59a665201296
Revises: fcf8f041589b
Create Date: 2026-06-04 17:01:51.614426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59a665201296'
down_revision = 'fcf8f041589b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_check_in_planned_utc'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_scheduled_for_utc'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('received_by_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_payments_created_at_utc'))
        batch_op.drop_index(batch_op.f('ix_payments_received_by_id'))

    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_movements_timestamp_utc'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_movements_timestamp_utc'), ['timestamp_utc'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_received_by_id'), ['received_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_created_at_utc'), ['created_at_utc'], unique=False)
        batch_op.alter_column('received_by_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_scheduled_for_utc'), ['scheduled_for_utc'], unique=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_check_in_planned_utc'), ['check_in_planned_utc'], unique=False)

    # ### end Alembic commands ###
