"""cleaning_cleaners: a villa is cleaned by more than one person

Revision ID: 5c3f9c4ee345
Revises: e4cbd4c10293
Create Date: 2026-09-14 16:00:18.288747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3f9c4ee345'
down_revision = 'e4cbd4c10293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaning_cleaners',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('cleaning_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('is_lead', sa.Boolean(), nullable=False),
    sa.Column('added_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cleaning_id'], ['cleaning_statuses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cleaning_id', 'user_id', name='uq_cleaning_cleaner')
    )
    with op.batch_alter_table('cleaning_cleaners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cleaning_cleaners_cleaning_id'), ['cleaning_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cleaning_cleaners_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_cleaners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cleaning_cleaners_user_id'))
        batch_op.drop_index(batch_op.f('ix_cleaning_cleaners_cleaning_id'))

    op.drop_table('cleaning_cleaners')
    # ### end Alembic commands ###
