"""add pack_size pack_unit category to inventory_items

Revision ID: 630d80a2baa0
Revises: 2ec75d138772
Create Date: 2026-06-17 12:04:47.704807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '630d80a2baa0'
down_revision = '2ec75d138772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pack_size', sa.Numeric(precision=12, scale=4), nullable=True))
        batch_op.add_column(sa.Column('pack_unit', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('pack_unit')
        batch_op.drop_column('pack_size')

    # ### end Alembic commands ###
