"""chunk 4 finance cashier reconciliation budgets

Revision ID: 69642070071a
Revises: d279d1e782bf
Create Date: 2026-05-28 16:44:59.831857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69642070071a'
down_revision = 'd279d1e782bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('set_by_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_budget_amount_nonneg'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['set_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_id', 'period', name='uq_budget_dept_period')
    )
    op.create_table('cash_reconciliations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('staff_id', sa.String(length=36), nullable=False),
    sa.Column('reconciled_by_id', sa.String(length=36), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('period_start_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('actual_amount >= 0', name='ck_cashrecon_actual_nonneg'),
    sa.CheckConstraint('expected_amount >= 0', name='ck_cashrecon_expected_nonneg'),
    sa.ForeignKeyConstraint(['reconciled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('period_closes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('period_start_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_by_id', sa.String(length=36), nullable=False),
    sa.Column('safe_count', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('expected_total_cash', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('difference', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('safe_count >= 0', name='ck_periodclose_safe_nonneg'),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('cash_recon_payments',
    sa.Column('recon_id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['recon_id'], ['cash_reconciliations.id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('payment_reconciliations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('matched', sa.Boolean(), nullable=False),
    sa.Column('matched_by_id', sa.String(length=36), nullable=True),
    sa.Column('statement_ref', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['matched_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_reconciliations')
    op.drop_table('cash_recon_payments')
    op.drop_table('period_closes')
    op.drop_table('cash_reconciliations')
    op.drop_table('budgets')
    # ### end Alembic commands ###
