"""cleaning_status

Revision ID: 7841e635503f
Revises: 3fae5c3ad830
Create Date: 2026-06-24 01:32:18.722865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7841e635503f'
down_revision = '3fae5c3ad830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleaning_statuses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('assigned_to_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('inspected_by_id', sa.String(length=36), nullable=True),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspected_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['bookable_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cleaning_statuses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cleaning_statuses_resource_id'), ['resource_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cleaning_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cleaning_statuses_resource_id'))

    op.drop_table('cleaning_statuses')
    # ### end Alembic commands ###
