"""inventory cost per unit and recipe lines

Revision ID: 7ab460c21a36
Revises: a868b6111792
Create Date: 2026-06-16 20:13:06.637803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab460c21a36'
down_revision = 'a868b6111792'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('menu_item_id', sa.String(length=36), nullable=False),
    sa.Column('inventory_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_recipe_line_qty_positive'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recipe_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recipe_lines_menu_item_id'), ['menu_item_id'], unique=False)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost_per_unit', sa.Numeric(precision=14, scale=4), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('cost_per_unit')

    with op.batch_alter_table('recipe_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipe_lines_menu_item_id'))

    op.drop_table('recipe_lines')
    # ### end Alembic commands ###
