"""An event is a customer with its own bill and menu

event_menu_lines: dish × plates planned ahead, with a RECORDED discount (menu
price, discount per plate, reason, who) and the order line it became once sent.
events.tab_id: the event's own bill (TabType.EVENT).
purchase_requests.event_id: a buy list knows which event it is for.

The two added columns get their foreign keys the same way as f5310690ca3a and
7c1d4e2f9a30: in place on Postgres; SQLite cannot add one without a rebuild
that FK enforcement blocks, and create_all() gives a fresh dev DB the FK anyway.

Revision ID: 8261a12ee61c
Revises: f5310690ca3a
Create Date: 2026-09-17 15:07:34.429969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8261a12ee61c'
down_revision = 'f5310690ca3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_menu_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('menu_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('menu_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_per_unit', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_reason', sa.String(length=200), nullable=True),
    sa.Column('discount_by_id', sa.String(length=36), nullable=True),
    sa.Column('order_item_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('discount_per_unit <= menu_price', name='ck_eventmenu_discount_le_price'),
    sa.CheckConstraint('discount_per_unit >= 0', name='ck_eventmenu_discount_nonneg'),
    sa.CheckConstraint('quantity > 0', name='ck_eventmenu_qty_pos'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['discount_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_menu_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_menu_lines_event_id'), ['event_id'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_id', sa.String(length=36), nullable=True))

    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_purchase_requests_event_id'), ['event_id'], unique=False)

    if op.get_bind().dialect.name != 'sqlite':
        op.create_foreign_key('fk_events_tab_id_tabs', 'events', 'tabs', ['tab_id'], ['id'])
        op.create_foreign_key('fk_purchase_requests_event_id_events', 'purchase_requests',
                              'events', ['event_id'], ['id'])


def downgrade():
    if op.get_bind().dialect.name != 'sqlite':
        op.drop_constraint('fk_purchase_requests_event_id_events', 'purchase_requests', type_='foreignkey')
        op.drop_constraint('fk_events_tab_id_tabs', 'events', type_='foreignkey')
    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_requests_event_id'))
        batch_op.drop_column('event_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('tab_id')

    with op.batch_alter_table('event_menu_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_menu_lines_event_id'))

    op.drop_table('event_menu_lines')
