"""chunk 9 conduct disputes feedback calendar

Revision ID: 8a0894874ea2
Revises: 8ea1b4353d99
Create Date: 2026-05-29 14:55:33.951766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0894874ea2'
down_revision = '8ea1b4353d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date_start_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_end_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_type', sa.String(length=25), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_peak', sa.Boolean(), nullable=False),
    sa.Column('planning_trigger_offset_days', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('date_end_utc >= date_start_utc', name='ck_calendar_end_after_start'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conduct_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rule_key', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('version > 0', name='ck_conduct_rule_version_pos'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_key', 'version', name='uq_conduct_rule_key_version')
    )
    with op.batch_alter_table('conduct_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conduct_rules_rule_key'), ['rule_key'], unique=False)

    op.create_table('conduct_signatures',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('conduct_rule_id', sa.String(length=36), nullable=False),
    sa.Column('signed_proof', sa.String(length=200), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('signed_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conduct_rule_id'], ['conduct_rules.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'conduct_rule_id', name='uq_signature_employee_rule'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('conduct_signatures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conduct_signatures_employee_id'), ['employee_id'], unique=False)

    op.create_table('disputes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reporter_employee_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('is_owner_only', sa.Boolean(), nullable=False),
    sa.Column('assigned_to_employee_id', sa.String(length=36), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_employee_id'], ['employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['reporter_employee_id'], ['employee_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disputes_reporter_employee_id'), ['reporter_employee_id'], unique=False)

    op.create_table('dispute_subjects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dispute_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['dispute_id'], ['disputes.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispute_id', 'employee_id', name='uq_dispute_subject')
    )
    with op.batch_alter_table('dispute_subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispute_subjects_dispute_id'), ['dispute_id'], unique=False)

    op.create_table('guest_feedback',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('guest_name', sa.String(length=200), nullable=False),
    sa.Column('guest_phone', sa.String(length=30), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('served_by_employee_id', sa.String(length=36), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='ck_feedback_score_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['served_by_employee_id'], ['employee_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_feedback')
    with op.batch_alter_table('dispute_subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispute_subjects_dispute_id'))

    op.drop_table('dispute_subjects')
    with op.batch_alter_table('disputes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disputes_reporter_employee_id'))

    op.drop_table('disputes')
    with op.batch_alter_table('conduct_signatures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conduct_signatures_employee_id'))

    op.drop_table('conduct_signatures')
    with op.batch_alter_table('conduct_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conduct_rules_rule_key'))

    op.drop_table('conduct_rules')
    op.drop_table('calendar_entries')
    # ### end Alembic commands ###
