"""Add tab assignment and employee payment account fields

Revision ID: 8e94a7bbcb48
Revises: b98f1a446346
Create Date: 2026-08-25 16:38:45.183452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e94a7bbcb48'
down_revision = 'b98f1a446346'
branch_labels = None
depends_on = None


def upgrade():
    # Plain ADD COLUMN only (no create_foreign_key / alter_column calls) — SQLite
    # handles this in-place. The moment a batch block also asks for a new FK
    # CONSTRAINT (not just an FK-typed column), Alembic's SQLite batch mode
    # switches to full table-recreate (CREATE temp -> COPY -> DROP -> RENAME),
    # which fails here with "FOREIGN KEY constraint failed" on `DROP TABLE tabs`
    # because charges/payments/orders hold live FKs into tabs. Declaring the FK
    # inline on the Column (still enforced by SQLAlchemy/the app) avoids that
    # recreate path entirely.
    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_account_number', sa.String(length=60), nullable=True))

    # No FK constraint here (deliberately): SQLite can only add one via a full
    # table recreate, which fails on `DROP TABLE tabs` — charges/payments/orders
    # hold live FKs into this table. The model still declares
    # ForeignKey('users.id') for ORM relationship/join use; existence is
    # validated at the application layer in the /assign endpoint instead,
    # same as manual_clock's employee_id check in app/hr/clock.py.
    with op.batch_alter_table('tabs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('assigned_at_utc', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabs', schema=None) as batch_op:
        batch_op.drop_column('assigned_at_utc')
        batch_op.drop_column('assigned_to_id')

    with op.batch_alter_table('employee_profiles', schema=None) as batch_op:
        batch_op.drop_column('payment_account_number')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
