"""chunk 8 events assignments notifications suggestions

Revision ID: 8ea1b4353d99
Revises: e4ad657bffe6
Create Date: 2026-05-29 14:21:32.951484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ea1b4353d99'
down_revision = 'e4ad657bffe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_types',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notification_channel_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('channel_name', sa.String(length=25), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_name')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('recipient_user_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=25), nullable=True),
    sa.Column('reference_type', sa.String(length=25), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('scheduled_for_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_recipient_user_id'), ['recipient_user_id'], unique=False)

    op.create_table('suggestions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('submitted_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('submitted_by_name', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=15), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_to_submitter', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('event_type_id', sa.String(length=36), nullable=False),
    sa.Column('booking_id', sa.String(length=36), nullable=True),
    sa.Column('starts_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expected_guests', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('ends_at_utc > starts_at_utc', name='ck_event_end_after_start'),
    sa.CheckConstraint('expected_guests > 0', name='ck_event_guests_pos'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('event_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('role_on_event', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_profiles.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_assignments_event_id'), ['event_id'], unique=False)

    op.create_table('event_inventory_allocations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('inventory_item_id', sa.String(length=36), nullable=False),
    sa.Column('allocated_quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('allocated_quantity > 0', name='ck_alloc_qty_pos'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('event_inventory_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_inventory_allocations_event_id'), ['event_id'], unique=False)

    op.create_table('event_stock_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('allocation_id', sa.String(length=36), nullable=False),
    sa.Column('movement_id', sa.String(length=36), nullable=False),
    sa.Column('movement_type', sa.String(length=10), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['event_inventory_allocations.id'], ),
    sa.ForeignKeyConstraint(['movement_id'], ['stock_movements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movement_id')
    )
    with op.batch_alter_table('event_stock_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_stock_movements_allocation_id'), ['allocation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_stock_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_stock_movements_allocation_id'))

    op.drop_table('event_stock_movements')
    with op.batch_alter_table('event_inventory_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_inventory_allocations_event_id'))

    op.drop_table('event_inventory_allocations')
    with op.batch_alter_table('event_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_assignments_event_id'))

    op.drop_table('event_assignments')
    op.drop_table('events')
    op.drop_table('suggestions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_user_id'))

    op.drop_table('notifications')
    op.drop_table('notification_channel_configs')
    op.drop_table('event_types')
    # ### end Alembic commands ###
