"""stage3: inventory_item.created_at + count_demotions table

Revision ID: 943bcf64838d
Revises: 7ab460c21a36
Create Date: 2026-06-17 01:26:53.294925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943bcf64838d'
down_revision = '7ab460c21a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('count_demotions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=36), nullable=False),
    sa.Column('demoted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('demoted_by_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['demoted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('count_demotions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_count_demotions_item_id'), ['item_id'], unique=False)

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('count_demotions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_count_demotions_item_id'))

    op.drop_table('count_demotions')
    # ### end Alembic commands ###
