"""waivers: a day guest holds a wristband, not a booking

Revision ID: b6f99a94b64d
Revises: 308b888ddceb
Create Date: 2026-09-14 21:50:48.992741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f99a94b64d'
down_revision = '308b888ddceb'
branch_labels = None
depends_on = None


def upgrade():
    # batch_alter_table is REQUIRED here, unlike a plain add_column: booking_id
    # goes from NOT NULL to nullable and SQLite cannot ALTER COLUMN, so the
    # table genuinely has to be rebuilt.
    #
    # The rebuild is also the only place the new CHECK can be installed. It is
    # added explicitly because alembic does not autogenerate check constraints,
    # and without it the rule "a waiver belongs to exactly one of a booking or a
    # tab" would live only in the model — which is app-level, and this codebase
    # puts a business rule in the database wherever it can be one.
    with op.batch_alter_table('waivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tab_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('booking_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_waivers_tab_id'), ['tab_id'], unique=False)
        batch_op.create_check_constraint(
            'ck_waiver_booking_xor_tab',
            '(booking_id IS NOT NULL AND tab_id IS NULL) OR '
            '(booking_id IS NULL AND tab_id IS NOT NULL)',
        )

    # Existing rows all carry a booking_id and no tab_id, so every one of them
    # already satisfies the constraint — no backfill needed.


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waivers', schema=None) as batch_op:
        batch_op.drop_constraint('ck_waiver_booking_xor_tab', type_='check')
        batch_op.drop_index(batch_op.f('ix_waivers_tab_id'))
        batch_op.alter_column('booking_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.drop_column('tab_id')

    # ### end Alembic commands ###
