"""Add idempotency_key to waivers

Revision ID: b98f1a446346
Revises: 79462d07a530
Create Date: 2026-08-24 20:42:13.893943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98f1a446346'
down_revision = '79462d07a530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idempotency_key', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_waivers_idempotency_key', ['idempotency_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waivers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_waivers_idempotency_key', type_='unique')
        batch_op.drop_column('idempotency_key')

    # ### end Alembic commands ###
