"""chunk 7 gate wristbands entry credit

Revision ID: e4ad657bffe6
Revises: 3ea9e71a2a1e
Create Date: 2026-05-29 08:34:31.263480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ad657bffe6'
down_revision = '3ea9e71a2a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wristband_counters',
    sa.Column('issue_date', sa.String(length=10), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('issue_date')
    )
    op.create_table('gate_headcounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('count_date', sa.String(length=10), nullable=False),
    sa.Column('counted', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('counted >= 0', name='ck_headcount_nonneg'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('count_date')
    )
    op.create_table('wristbands',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('band_number', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.String(length=10), nullable=False),
    sa.Column('issued_by_id', sa.String(length=36), nullable=False),
    sa.Column('entry_payment_id', sa.String(length=36), nullable=False),
    sa.Column('tab_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('deactivated_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_by_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('band_number > 0', name='ck_wristband_number_pos'),
    sa.ForeignKeyConstraint(['deactivated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entry_payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tab_id'], ['tabs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('band_number', 'issue_date', name='uq_wristband_number_date'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_table('gate_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wristband_id', sa.String(length=36), nullable=False),
    sa.Column('head_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('head_count > 0', name='ck_gate_entry_count_pos'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wristband_id'], ['wristbands.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wristband_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gate_entries')
    op.drop_table('wristbands')
    op.drop_table('gate_headcounts')
    op.drop_table('wristband_counters')
    # ### end Alembic commands ###
