"""InventoryItem.is_alcoholic — liquor stock lines a manager signs for

Revision ID: e4cbd4c10293
Revises: 3fcff8c95b91
Create Date: 2026-09-10 23:03:48.286151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4cbd4c10293'
down_revision = '3fcff8c95b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Plain ADD COLUMN, deliberately NOT batch_alter_table. A batch op rebuilds
    # the whole table (create tmp, copy, DROP original, rename), and on SQLite
    # the DROP fails against the foreign keys pointing at inventory_items — it
    # died half way and left _alembic_tmp_inventory_items behind, which then
    # blocked every retry. Adding one nullable-with-default column needs no
    # rebuild, and reads the same on Postgres.
    #
    # server_default is required: the table already holds rows, and a NOT NULL
    # column with no default cannot be added to them. Existing stock is assumed
    # NOT liquor — a manager marks the bottles deliberately, which is the point.
    op.add_column('inventory_items',
                  sa.Column('is_alcoholic', sa.Boolean(), nullable=False,
                            server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_column('is_alcoholic')

    # ### end Alembic commands ###
