"""Charge.tax_rate_snapshot: VAT frozen per sale

Nullable ON PURPOSE, and NOT backfilled.

Every charge that already exists was recorded before VAT was tracked, and this
migration does not know what rate applied to it or whether the item was
standard-rated, zero-rated or exempt. Stamping 16% across the history would
manufacture a tax position the resort never actually took, and it would look
exactly like real data to whoever files the return.

NULL therefore means "predates VAT tracking" and the summary reports it as its
own line, so the gap is visible instead of quietly folded into the totals.

Revision ID: e88eb8ef1962
Revises: 9b2e5c71f40a
Create Date: 2026-08-27 04:34:06.902968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e88eb8ef1962'
down_revision = '9b2e5c71f40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_rate_snapshot', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('charges', schema=None) as batch_op:
        batch_op.drop_column('tax_rate_snapshot')

    # ### end Alembic commands ###
