"""add lost_found, suppliers tables and menu/purchase columns

Revision ID: e9d9170f7c89
Revises: 7841e635503f
Create Date: 2026-06-25 18:14:12.529995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d9170f7c89'
down_revision = '7841e635503f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('items_supplied', sa.String(length=500), nullable=True),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('lost_found',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('found_location', sa.String(length=200), nullable=False),
    sa.Column('found_by_id', sa.String(length=36), nullable=False),
    sa.Column('found_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('claimed_by_name', sa.String(length=200), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['found_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allergens', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('dietary_flags', sa.String(length=200), nullable=True))

    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_purchase_requests_supplier_id', 'suppliers', ['supplier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_purchase_requests_supplier_id', type_='foreignkey')
        batch_op.drop_column('supplier_id')

    with op.batch_alter_table('menu_items', schema=None) as batch_op:
        batch_op.drop_column('dietary_flags')
        batch_op.drop_column('allergens')

    op.drop_table('lost_found')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
