"""chunk 10 equipment dashboard indexes

Revision ID: fcf8f041589b
Revises: 8a0894874ea2
Create Date: 2026-05-29 15:24:52.967221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcf8f041589b'
down_revision = '8a0894874ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('equipment_type', sa.String(length=60), nullable=False),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('last_service_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_interval_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=False),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('performed_by_id', sa.String(length=36), nullable=False),
    sa.Column('performed_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_logs_equipment_id'), ['equipment_id'], unique=False)

    op.create_table('safety_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('equipment_id', sa.String(length=36), nullable=False),
    sa.Column('performed_by_id', sa.String(length=36), nullable=False),
    sa.Column('performed_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('checklist_notes', sa.Text(), nullable=True),
    sa.Column('created_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('safety_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_checks_equipment_id'), ['equipment_id'], unique=False)

    # Performance indexes on hot query columns
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index('ix_payments_created_at_utc', ['created_at_utc'], unique=False)
        batch_op.create_index('ix_payments_received_by_id', ['received_by_id'], unique=False)
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_scheduled_for_utc', ['scheduled_for_utc'], unique=False)
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index('ix_bookings_check_in_planned_utc', ['check_in_planned_utc'], unique=False)
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.create_index('ix_stock_movements_timestamp_utc', ['timestamp_utc'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movements', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_movements_timestamp_utc')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index('ix_bookings_check_in_planned_utc')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_scheduled_for_utc')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index('ix_payments_received_by_id')
        batch_op.drop_index('ix_payments_created_at_utc')
    with op.batch_alter_table('safety_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_checks_equipment_id'))

    op.drop_table('safety_checks')
    with op.batch_alter_table('maintenance_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_logs_equipment_id'))

    op.drop_table('maintenance_logs')
    op.drop_table('equipment')
    # ### end Alembic commands ###
